runtime: python39
service: phoneme-recognition

# Instance configuration for model loading
instance_class: F4_1G  # Higher memory for Wav2Vec2 model
automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  FLASK_ENV: production

# Static file handlers
handlers:
  # Serve static files with caching
  - url: /static
    static_dir: static
    secure: always
    expiration: '1d'
  
  # Main application handler
  - url: /.*
    script: auto
    secure: always

# Skip files to reduce deployment size
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?tests/.*$
  - ^(.*/)?test_.*\.py$
  - ^(.*/)?venv/.*$
  - ^(.*/)?env/.*$
  - ^(.*/)?__pycache__/.*$
  - node_modules/
  - \.git/